### PR TITLE
No more sending on closed channels during checkscontroller shutdown

### LINKED ISSUE #244: Bug: Sparrow's shutdown sends signal on closed channel
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The sparow's `ChecksController` method to shutdown the check's one by one fails to shutdown all checks and makes the sparrow panic. This only happens if more than one check has been registered with the sparrow.

### Expected Behavior

The sparrow should be able to shutdown gracefully in case of an unexpected error/ signal.

### Steps To Reproduce

1. Send keyboard interrupt to sparrow while running (Ctrl+C)
2. panic happens once of the registered check's `Shutdown` method get's called

### Relevant logs and/or screenshots, environment information, etc.

The logs show the panic happening for the latency check and almost give away the reason behind this weird behavior:

```shell
^Ctime=16:39:31 level=INFO source=/Users/puffito/dev/repos/sparrow/cmd/run.go:96 msg="Signal received, shutting down"
time=16:39:31 level=INFO source=/Users/puffito/dev/repos/sparrow/pkg/sparrow/run.go:184 msg="Shutting down sparrow gracefully"
time=16:39:31 level=DEBUG source=/Users/puffito/dev/repos/sparrow/pkg/sparrow/targets/manager.go:127 msg="Shut down signal received"
time=16:39:31 level=ERROR source=/Users/puffito/dev/repos/sparrow/pkg/checks/dns/dns.go:92 msg="Context canceled" err="context canceled"
time=16:39:31 level=ERROR source=/Users/puffito/dev/repos/sparrow/pkg/sparrow/controller.go:146 msg="Failed to run check" check=dns error="context canceled"
time=16:39:31 level=ERROR source=/Users/puffito/dev/repos/sparrow/pkg/checks/latency/latency.go:82 msg="Context canceled" err="context canceled"
time=16:39:31 level=DEBUG source=/Users/puffito/dev/repos/sparrow/pkg/sparrow/targets/manager.go:148 msg="Stopping gitlab reconciliation routine"
time=16:39:31 level=ERROR source=/Users/puffito/dev/repos/sparrow/pkg/sparrow/controller.go:146 msg="Failed to run check" check=latency error="context canceled"
time=16:39:31 level=ERROR source=/Users/puffito/dev/repos/sparrow/pkg/sparrow/targets/manager.go:86 msg="Error while reconciling targets" err="context canceled"
time=16:39:31 level=ERROR source=/Users/puffito/dev/repos/sparrow/pkg/checks/health/health.go:80 msg="Context canceled" err="context canceled"
time=16:39:31 level=ERROR source=/Users/puffito/dev/repos/sparrow/pkg/sparrow/controller.go:146 msg="Failed to run check" check=health error="context canceled"
time=16:39:31 level=ERROR source=/Users/puffito/dev/repos/sparrow/pkg/api/api.go:110 msg="Failed to serve api" error="http: Server closed" scheme=http
time=16:39:31 level=DEBUG source=/Users/puffito/dev/repos/sparrow/pkg/sparrow/metrics/metrics.go:132 msg="Tracing shutdown"
time=16:39:31 level=DEBUG source=/Users/puffito/dev/repos/sparrow/pkg/config/file.go:135 msg="Sending signal to shut down file loader"
time=16:39:31 level=INFO source=/Users/puffito/dev/repos/sparrow/pkg/sparrow/controller.go:84 msg="Shutting down checks controller"
time=16:39:31 level=ERROR source=/Users/puffito/dev/repos/sparrow/pkg/sparrow/controller.go:164 msg="Could not remove metrics collector from registry" check=latency
time=16:39:31 level=ERROR source=/Users/puffito/dev/repos/sparrow/pkg/sparrow/controller.go:164 msg="Could not remove metrics collector from registry" check=latency
time=16:39:31 level=ERROR source=/Users/puffito/dev/repos/sparrow/pkg/sparrow/controller.go:164 msg="Could not remove metrics collector from registry" check=latency
panic: send on closed channel

goroutine 8 [running]:
github.com/caas-team/sparrow/pkg/checks/latency.(*Latency).Shutdown(0x14000416000)
        /Users/puffito/dev/repos/sparrow/pkg/checks/latency/latency.go:102 +0x2c
github.com/caas-team/sparrow/pkg/sparrow.(*ChecksController).UnregisterCheck(0x140002788c0, {0x1054300c8, 0x1400033e380}, {0x105435a58, 0x14000416000})
        /Users/puffito/dev/repos/sparrow/pkg/sparrow/controller.go:168 +0x144
github.com/caas-team/sparrow/pkg/sparrow.(*ChecksController).Shutdown(0x140002788c0, {0x1054300c8, 0x1400033e380})
        /Users/puffito/dev/repos/sparrow/pkg/sparrow/controller.go:87 +0x80
github.com/caas-team/sparrow/pkg/sparrow.(*Sparrow).shutdown.func1()
        /Users/puffito/dev/repos/sparrow/pkg/sparrow/run.go:192 +0x118
sync.(*Once).doSlow(0x10542fed0?, 0x1059c1ca0?)
        /opt/homebrew/opt/go/libexec/src/sync/once.go:76 +0xf8
sync.(*Once).Do(...)
        /opt/homebrew/opt/go/libexec/src/sync/once.go:67
github.com/caas-team/sparrow/pkg/sparrow.(*Sparrow).shutdown(0x1400022c480, {0x105430020, 0x140003f09c0})
        /Users/puffito/dev/repos/sparrow/pkg/sparrow/run.go:183 +0xd0
github.com/caas-team/sparrow/pkg/sparrow.(*Sparrow).Run(0x1400022c480, {0x105430020?, 0x140000f2de0?})
        /Users/puffito/dev/repos/sparrow/pkg/sparrow/run.go:127 +0x368
github.com/caas-team/sparrow/cmd.NewCmdRun.run.func1.1()
        /Users/puffito/dev/repos/sparrow/cmd/run.go:91 +0x30
created by github.com/caas-team/sparrow/cmd.NewCmdRun.run.func1 in goroutine 1
        /Users/puffito/dev/repos/sparrow/cmd/run.go:90 +0x240

Process finished with the exit code 2
```

### Who can address the issue?

_No response_

### Anything else?

The error happens because the controller iterates over the actual slice of `Checks`, which the `Iter()` function returns. Since the Checks get immediately removed from the internal `checks` slice after being unregistered (see the `ChecksController` `UnregisterCheck` method), the referenced slice with the checks get's modified and we end up trying to delete the same check twice.

Adding a simple debug log in the UnregisterCheck confirms the suspicion. The healthcheck is being unregistered twice in a row in the logs below, which shouldn't happen, as the shutdown is only called once (with the sync.Once) in the sparrow and the `ChecksController` just iterates over the current checks. 

```
time=16:53:07 level=INFO source=/Users/puffito/dev/repos/sparrow/pkg/sparrow/controller.go:84 msg="Shutting down checks controller"
time=16:53:07 level=DEBUG source=/Users/puffito/dev/repos/sparrow/pkg/sparrow/controller.go:160 msg="Unregistering check" check=latency
time=16:53:07 level=DEBUG source=/Users/puffito/dev/repos/sparrow/pkg/sparrow/controller.go:160 msg="Unregistering check" check=health
time=16:53:07 level=DEBUG source=/Users/puffito/dev/repos/sparrow/pkg/sparrow/controller.go:160 msg="Unregistering check" check=health
time=16:53:07 level=ERROR source=/Users/puffito/dev/repos/sparrow/pkg/sparrow/controller.go:164 msg="Could not remove metrics collector from registry" check=health
```

Given the asynchronous nature of how the shutdown of the check's works (sending a signal in a channel), a simple way to deal with this is to get a copy of the `checks` slice when calling the `Iter()` function.

### PR DESCRIPTION
**Pull request by puffitos**
## Motivation

Fixes #244

## Changes

The change is just one LoC: return a copy of the `checks` slice when calling `Iter()`, which TBH is a safer and simpler way to handle this slice (long live functional programming).

The rest is just some light housekeeping:

- Adding context to the logs
- Adding a "sparrow was shutdown" log message to know that everything went well after shutting down the sparrow; currently nothing is being shown as feedback to the user outside an exit code of 0.

## Tests done

The manual test case mentioned in the issue was carried out; started the sparrow and sent a keyboard interrupt. The error doesn't occur anymore:

```shell
time=17:07:25 level=INFO source=/Users/puffito/dev/repos/sparrow/pkg/sparrow/run.go:185 msg="Shutting down sparrow"
time=17:07:25 level=DEBUG source=/Users/puffito/dev/repos/sparrow/pkg/sparrow/targets/manager.go:154 msg="Shut down signal received"
time=17:07:25 level=DEBUG source=/Users/puffito/dev/repos/sparrow/pkg/sparrow/targets/remote/gitlab/gitlab.go:335 msg="Deleting file from gitlab" file="{AuthorEmail:dev.telekom.de@sparrow AuthorName:dev.telekom.de CommitMessage:Unregistering global target Content:{Url: LastSeen:0001-01-01 00:00:00 +0000 UTC} Name:dev.telekom.de.json}"
time=17:07:25 level=ERROR source=/Users/puffito/dev/repos/sparrow/pkg/checks/latency/latency.go:82 msg="Context canceled" err="context canceled"
time=17:07:25 level=ERROR source=/Users/puffito/dev/repos/sparrow/pkg/sparrow/controller.go:146 msg="Failed to run check" check=latency error="context canceled"
time=17:07:26 level=INFO source=/Users/puffito/dev/repos/sparrow/pkg/sparrow/targets/manager.go:172 msg="Successfully unregistered as global target"
time=17:07:26 level=DEBUG source=/Users/puffito/dev/repos/sparrow/pkg/sparrow/targets/manager.go:177 msg="Stopping gitlab reconciliation routine"
time=17:07:26 level=ERROR source=/Users/puffito/dev/repos/sparrow/pkg/api/api.go:110 msg="Failed to serve api" error="http: Server closed" scheme=http
time=17:07:26 level=DEBUG source=/Users/puffito/dev/repos/sparrow/pkg/sparrow/metrics/metrics.go:132 msg="Tracing shutdown"
time=17:07:26 level=DEBUG source=/Users/puffito/dev/repos/sparrow/pkg/config/file.go:135 msg="Sending signal to shut down file loader"
time=17:07:26 level=INFO source=/Users/puffito/dev/repos/sparrow/pkg/sparrow/controller.go:84 msg="Shutting down checks controller"
time=17:07:26 level=ERROR source=/Users/puffito/dev/repos/sparrow/pkg/sparrow/run.go:130 msg="Non-recoverable error in sparrow component" error="failed serving API: context canceled"
time=17:07:26 level=INFO source=/Users/puffito/dev/repos/sparrow/pkg/sparrow/run.go:134 msg="Sparrow was shut down"

Process finished with the exit code 0
```

Additionally, I've added a new unit test case (which does fail in the main branch ATM). The test actually tests the shutdown function of the `ChecksController`, which we had unfortunately neglected.

- [x] Unit tests succeeded
- [x] E2E tests succeeded

## TODO

- [x] I've assigned this PR to myself
- [x] I've labeled this PR correctly

### CODE REVIEW

**Review by y-eight — APPROVED** [review]
LGTM

File: pkg/checks/runtime/checks.go [hunk 1]
```diff
@@ -53,5 +54,5 @@ func (c *Checks) Delete(check checks.Check) {
 func (c *Checks) Iter() []checks.Check {
 	c.mu.RLock()
 	defer c.mu.RUnlock()
-	return c.checks
+	return slices.Clone(c.checks)
```
Comment (lvlcn-t) [inline pkg/checks/runtime/checks.go:57]: AFAIK will this be a problem. When `slices.Clone(c.checks)` is called, it creates a copy of the checks. Any updates applied to these cloned instances will not affect the original running instances. This means that the original checks will never receive the updated configurations, which can prevent them from functioning correctly.

**Review by lvlcn-t — CHANGES_REQUESTED** [review]

File: pkg/checks/runtime/checks.go (hunk 1 above)
Comment (puffitos) [reply pkg/checks/runtime/checks.go:57]: I'll write some tests to replicate the problem. And then we can talk about how to better fix this.

Comment (puffitos) [reply pkg/checks/runtime/checks.go:57]: Good news: the tests show that the change works as intended. Or at least I think they do :)

The shallow copy still provides a slice with the references intact. Each check instance will run its `UpdateConfig` and the actual check in the `checks` field of the controller will get updated.

Comment (puffitos) [reply pkg/checks/runtime/checks.go:57]: Thanks, it was the next thing on my list. Let's sit down after you're done with your exams and talk about your e2e branch 🌿

Comment (lvlcn-t) [reply pkg/checks/runtime/checks.go:57]: The tests were also successful.

### Manual E2E Test

First I've started the sparrow with only 2 health check targets and then updated the runtime config after the first interval to include two additional targets:
```log
time=11:04:39 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:193 msg="Starting retry routine to get health status" target=https://www.google.com
time=11:04:39 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:193 msg="Starting retry routine to get health status" target=https://www.example.com
time=11:04:39 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:199 msg="Successfully got health status of target" target=https://www.example.com status=healthy
time=11:04:39 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:199 msg="Successfully got health status of target" target=https://www.google.com status=healthy
time=11:04:39 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:211 msg="Successfully got health status from all targets"
time=11:04:39 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:95 msg="Successfully finished health check run"
```
After I added the two additional targets:
```log
time=11:05:09 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:166 msg="Checking health"
time=11:05:09 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:171 msg="Getting health status for each target in separate routine" amount=4
time=11:05:09 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:208 msg="Waiting for all routines to finish"
time=11:05:09 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:193 msg="Starting retry routine to get health status" target=https://www.google.com
time=11:05:09 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:193 msg="Starting retry routine to get health status" target=https://www.example.com
time=11:05:09 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:193 msg="Starting retry routine to get health status" target=https://www.telekom.de
time=11:05:09 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:193 msg="Starting retry routine to get health status" target=https://gitlab.devops.telekom.de
time=11:05:09 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:199 msg="Successfully got health status of target" target=https://www.example.com status=healthy
time=11:05:09 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:199 msg="Successfully got health status of target" target=https://www.google.com status=healthy
time=11:05:09 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:199 msg="Successfully got health status of target" target=https://www.telekom.de status=healthy
time=11:05:10 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:199 msg="Successfully got health status of target" target=https://gitlab.devops.telekom.de status=healthy
time=11:05:10 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:211 msg="Successfully got health status from all targets"
time=11:05:10 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:95 msg="Successfully finished health check run"
```

<details>
<summary>Complete log</summary>

```bash
❯ go run . run -c ./.tmp/.sparrow.yaml
Using config file: ./.tmp/.sparrow.yaml
time=11:04:09 level=INFO source=/home/installadm/dev/sparrow/cmd/run.go:89 msg="Running sparrow"
time=11:04:09 level=DEBUG source=/home/installadm/dev/sparrow/pkg/sparrow/metrics/metrics.go:117 msg="Tracing initialized with new provider" provider=http
time=11:04:09 level=INFO source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:76 msg="Starting healthcheck" interval=30s
time=11:04:09 level=INFO source=/home/installadm/dev/sparrow/pkg/api/api.go:101 msg="Serving Api" addr=:8081
time=11:04:39 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:166 msg="Checking health"
time=11:04:39 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:171 msg="Getting health status for each target in separate routine" amount=2
time=11:04:39 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:208 msg="Waiting for all routines to finish"
time=11:04:39 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:193 msg="Starting retry routine to get health status" target=https://www.google.com
time=11:04:39 level=INFO source=/home/installadm/dev/sparrow/pkg/config/file.go:93 msg="Successfully got local runtime configuration"
time=11:04:39 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:193 msg="Starting retry routine to get health status" target=https://www.example.com
time=11:04:39 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:199 msg="Successfully got health status of target" target=https://www.example.com status=healthy
time=11:04:39 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:199 msg="Successfully got health status of target" target=https://www.google.com status=healthy
time=11:04:39 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:211 msg="Successfully got health status from all targets"
time=11:04:39 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:95 msg="Successfully finished health check run"
time=11:05:09 level=INFO source=/home/installadm/dev/sparrow/pkg/config/file.go:93 msg="Successfully got local runtime configuration"
time=11:05:09 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:166 msg="Checking health"
time=11:05:09 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:171 msg="Getting health status for each target in separate routine" amount=4
time=11:05:09 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:208 msg="Waiting for all routines to finish"
time=11:05:09 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:193 msg="Starting retry routine to get health status" target=https://www.google.com
time=11:05:09 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:193 msg="Starting retry routine to get health status" target=https://www.example.com
time=11:05:09 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:193 msg="Starting retry routine to get health status" target=https://www.telekom.de
time=11:05:09 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:193 msg="Starting retry routine to get health status" target=https://gitlab.devops.telekom.de
time=11:05:09 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:199 msg="Successfully got health status of target" target=https://www.example.com status=healthy
time=11:05:09 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:199 msg="Successfully got health status of target" target=https://www.google.com status=healthy
time=11:05:09 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:199 msg="Successfully got health status of target" target=https://www.telekom.de status=healthy
time=11:05:10 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:199 msg="Successfully got health status of target" target=https://gitlab.devops.telekom.de status=healthy
time=11:05:10 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:211 msg="Successfully got health status from all targets"
time=11:05:10 level=DEBUG source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:95 msg="Successfully finished health check run"
^Ctime=11:05:19 level=INFO source=/home/installadm/dev/sparrow/cmd/run.go:96 msg="Signal received, shutting down"
time=11:05:19 level=ERROR source=/home/installadm/dev/sparrow/pkg/checks/health/health.go:80 msg="Context canceled" err="context canceled"
time=11:05:19 level=ERROR source=/home/installadm/dev/sparrow/pkg/sparrow/controller.go:146 msg="Failed to run check" check=health error="context canceled"
time=11:05:19 level=INFO source=/home/installadm/dev/sparrow/pkg/sparrow/run.go:185 msg="Shutting down sparrow"
time=11:05:19 level=ERROR source=/home/installadm/dev/sparrow/pkg/api/api.go:110 msg="Failed to serve api" error="http: Server closed" scheme=http
time=11:05:19 level=DEBUG source=/home/installadm/dev/sparrow/pkg/sparrow/metrics/metrics.go:132 msg="Tracing shutdown"
time=11:05:19 level=DEBUG source=/home/installadm/dev/sparrow/pkg/config/file.go:135 msg="Sending signal to shut down file loader"
time=11:05:19 level=INFO source=/home/installadm/dev/sparrow/pkg/sparrow/controller.go:84 msg="Shutting down checks controller"
time=11:05:19 level=INFO source=/home/installadm/dev/sparrow/pkg/sparrow/run.go:134 msg="Sparrow was shut down"
```

</details>

<details>
<summary>Used startup/runtime config</summary>

```yaml
name: sparrow.localhost

api:
  address: :8081

telemetry:
  exporter: http
  tls:
    enabled: true
  url: <redacted>

loader:
  type: file
  interval: 30s
  file:
    path: ./.tmp/.sparrow.yaml

health:
  interval: 30s
  timeout: 10s
  retry:
    count: 3
    delay: 1s
  targets:
    - https://www.example.com
    - https://www.google.com
    - https://www.telekom.de
    - https://gitlab.devops.telekom.de
```

</details>

**Review by lvlcn-t — APPROVED** [review]
